name: CI

on:
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Lint check
        run: npm run lint

      - name: Build
        run: npm run package:test

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-executable
          path: release/*.exe
