name: Build and Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    permissions:
      contents: write # Needed to create GitHub Releases

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Lint check
        run: npm run lint

      - name: Build (Dev / PR)
        if: ${{ !startsWith(github.ref, 'refs/tags/v') }}
        run: npm run package:test
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Artifacts (Dev / PR)
        if: ${{ !startsWith(github.ref, 'refs/tags/v') }}
        uses: actions/upload-artifact@v4
        with:
          name: windows-executable
          path: release/*.exe

      - name: Build and Publish Release
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        run: npm run package:publish
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
